name: Hadolint for Dockerfiles

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths: "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Hadolint protos dockerfile
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: protos/docker/Dockerfile
      - name: Hadoolint main dockerfile
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: Dockerfile
